/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusPersonIdRouteImport } from './routes/status.$personId'
import { Route as PeopleNewRouteImport } from './routes/people.new'
import { Route as GradePersonIdRouteImport } from './routes/grade.$personId'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusPersonIdRoute = StatusPersonIdRouteImport.update({
  id: '/status/$personId',
  path: '/status/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleNewRoute = PeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GradePersonIdRoute = GradePersonIdRouteImport.update({
  id: '/grade/$personId',
  path: '/grade/$personId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/unlock': typeof UnlockRoute
  '/grade/$personId': typeof GradePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/status/$personId': typeof StatusPersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/unlock': typeof UnlockRoute
  '/grade/$personId': typeof GradePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/status/$personId': typeof StatusPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/unlock': typeof UnlockRoute
  '/grade/$personId': typeof GradePersonIdRoute
  '/people/new': typeof PeopleNewRoute
  '/status/$personId': typeof StatusPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/unlock'
    | '/grade/$personId'
    | '/people/new'
    | '/status/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/unlock'
    | '/grade/$personId'
    | '/people/new'
    | '/status/$personId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/unlock'
    | '/grade/$personId'
    | '/people/new'
    | '/status/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  UnlockRoute: typeof UnlockRoute
  GradePersonIdRoute: typeof GradePersonIdRoute
  PeopleNewRoute: typeof PeopleNewRoute
  StatusPersonIdRoute: typeof StatusPersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$personId': {
      id: '/status/$personId'
      path: '/status/$personId'
      fullPath: '/status/$personId'
      preLoaderRoute: typeof StatusPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/new': {
      id: '/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof PeopleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade/$personId': {
      id: '/grade/$personId'
      path: '/grade/$personId'
      fullPath: '/grade/$personId'
      preLoaderRoute: typeof GradePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  UnlockRoute: UnlockRoute,
  GradePersonIdRoute: GradePersonIdRoute,
  PeopleNewRoute: PeopleNewRoute,
  StatusPersonIdRoute: StatusPersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
